### ISSUE TITLE
Methods Aren't in Library

### ISSUE THREAD

**Issue by chxp82q** [JP1016/SuperBadge#1]
Hello, your setImage method and other methods aren't in the library when I import them in gradle. I looked at your class, and the library I have misses the methods, but the class on your github has these methods. Please update this lib!

**Comment by JP1016** [comment]
Hi @JavaCafe01 , Thanks for reporting, made a new release containing these methods
`implementation 'com.github.JP1016:SuperBadge:v2'
`
